/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.gilgamesh.xena;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int calendar=0x7f020000;
        public static final int dotted_empty=0x7f020001;
        public static final int eraser=0x7f020002;
        public static final int exit=0x7f020003;
        public static final int gear=0x7f020004;
        public static final int hand=0x7f020005;
        public static final int right=0x7f020006;
        public static final int solid_empty=0x7f020007;
        public static final int solid_filled=0x7f020008;
        public static final int xena=0x7f020009;
    }
    public static final class id {
        public static final int file_picker_activity=0x7f040000;
        public static final int file_picker_activity_button_date=0x7f040001;
        public static final int file_picker_activity_button_settings=0x7f040002;
        public static final int file_picker_activity_button_svg=0x7f040004;
        public static final int file_picker_activity_edit_text=0x7f040003;
        public static final int file_picker_activity_layout_listing=0x7f040005;
        public static final int file_picker_activity_modal=0x7f040006;
        public static final int file_picker_activity_modal_button_cancel=0x7f04000b;
        public static final int file_picker_activity_modal_button_set=0x7f04000c;
        public static final int file_picker_activity_modal_edit_draw_refresh=0x7f040009;
        public static final int file_picker_activity_modal_edit_flick_distance=0x7f04000a;
        public static final int file_picker_activity_modal_edit_palm=0x7f040007;
        public static final int file_picker_activity_modal_edit_pan_update=0x7f040008;
        public static final int scribble_activity=0x7f04000d;
        public static final int scribble_activity_art_toggle=0x7f040013;
        public static final int scribble_activity_controls=0x7f04000f;
        public static final int scribble_activity_draw_erase_toggle=0x7f040015;
        public static final int scribble_activity_draw_pan_toggle=0x7f040011;
        public static final int scribble_activity_exit=0x7f040010;
        public static final int scribble_activity_modal=0x7f040016;
        public static final int scribble_activity_modal_button_cancel=0x7f04001a;
        public static final int scribble_activity_modal_button_set=0x7f04001b;
        public static final int scribble_activity_modal_edit_x=0x7f040017;
        public static final int scribble_activity_modal_edit_y=0x7f040018;
        public static final int scribble_activity_modal_edit_zoom=0x7f040019;
        public static final int scribble_activity_scribble_view=0x7f04000e;
        public static final int scribble_activity_text_path=0x7f040012;
        public static final int scribble_activity_text_status=0x7f040014;
    }
    public static final class layout {
        public static final int file_picker_activity=0x7f030000;
        public static final int file_picker_activity_modal=0x7f030001;
        public static final int scribble_activity=0x7f030002;
        public static final int scribble_activity_modal=0x7f030003;
    }
    public static final class string {
        public static final int xena_version=0x7f060000;
    }
    public static final class style {
        public static final int file_picker_pane_directory=0x7f050000;
        public static final int file_picker_pane_file=0x7f050001;
        public static final int file_picker_pane_row=0x7f050002;
    }
}
